
package com.zotyo.javatest.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1.6
 * 
 */
@XmlRootElement(name = "NoSuchTeamException", namespace = "http://javatest.zotyo.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoSuchTeamException", namespace = "http://javatest.zotyo.com/", propOrder = {
    "faultInfo",
    "message"
})
public class NoSuchTeamExceptionBean {

    private String faultInfo;
    private String message;

    /**
     * 
     * @return
     *     returns String
     */
    public String getFaultInfo() {
        return this.faultInfo;
    }

    /**
     * 
     * @param faultInfo
     *     the value for the faultInfo property
     */
    public void setFaultInfo(String faultInfo) {
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
