
package com.zotyo.diary.client;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Diary", targetNamespace = "http://ws.diary.zotyo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Diary {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "addEvent", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.AddEvent")
    public void addEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Event arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "addDay", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.AddDay")
    public void addDay(
        @WebParam(name = "arg0", targetNamespace = "")
        Day arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.zotyo.diary.client.Day>
     */
    @WebMethod
    @WebResult(name = "Day", targetNamespace = "")
    @RequestWrapper(localName = "getAllDaysInDiary", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.GetAllDaysInDiary")
    @ResponseWrapper(localName = "getAllDaysInDiaryResponse", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.GetAllDaysInDiaryResponse")
    public List<Day> getAllDaysInDiary();

    /**
     * 
     * @return
     *     returns java.util.List<com.zotyo.diary.client.Event>
     */
    @WebMethod
    @WebResult(name = "Event", targetNamespace = "")
    @RequestWrapper(localName = "getAllEvents", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.GetAllEvents")
    @ResponseWrapper(localName = "getAllEventsResponse", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.GetAllEventsResponse")
    public List<Event> getAllEvents();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.zotyo.diary.client.Day>
     */
    @WebMethod
    @WebResult(name = "Day", targetNamespace = "")
    @RequestWrapper(localName = "getDaysForAMonth", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.GetDaysForAMonth")
    @ResponseWrapper(localName = "getDaysForAMonthResponse", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.GetDaysForAMonthResponse")
    public List<Day> getDaysForAMonth(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.zotyo.diary.client.Event>
     */
    @WebMethod
    @WebResult(name = "Event", targetNamespace = "")
    @RequestWrapper(localName = "getEventsForADay", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.GetEventsForADay")
    @ResponseWrapper(localName = "getEventsForADayResponse", targetNamespace = "http://ws.diary.zotyo.com/", className = "com.zotyo.diary.client.GetEventsForADayResponse")
    public List<Event> getEventsForADay(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

}
